name: Automated Data Preprocessing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn
        
    # PENTING: Buat folder output yang akan digunakan oleh script
    - name: Create Output Folder
      run: |
        mkdir -p preprocessing/iris_preprocessing

    - name: Run Preprocessing Script
      id: run_script
      run: |
        # Definisi PATH menggunakan ${{ github.workspace }} untuk path ABSOLUT
        RAW_PATH=${{ github.workspace }}/namadataset_raw/Iris.csv
        OUTPUT_DIR=${{ github.workspace }}/preprocessing/iris_preprocessing
        
        # Jalankan script dengan argumen path ABSOLUT
        # Pastikan nama script sesuai: automate_peri.py
        python preprocessing/automate_peri.py "$RAW_PATH" "$OUTPUT_DIR"
        
    - name: Upload Processed Dataset Artifact
      uses: actions/upload-artifact@v4
      with:
        name: processed-iris-data
        # Path ini harus sesuai dengan output_dir + nama file
        path: preprocessing/iris_preprocessing/iris_processed_data.csv
        retention-days: 1
